services:
  database:
    image: "postgres:16.6-alpine3.21"
    env_file:
      - .env.example
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local_user -d local_db"]
      interval: 5s
      retries: 5
      timeout: 3s

  app:
    build: .
    env_file:
      - .env.example
    depends_on:
      database:
        condition: service_healthy
